OpenSCAP/oscap-anaconda-addon

org_fedora_oscap/common.py
Using anaconda's knowledge of what product and version this is we can dynamically select a more intelligent default SCAP guide.  This patch eliminates the need to customize the search location for RHEL (and other rebuilds).
=> Determine product automatically for selecting SCAP guide

org_fedora_oscap/ks/oscap.py
You can now use payload class in ``setup()`` and ``execute()`` methods.
=> Use new method signature with payload class

org_fedora_oscap/rule_handling.py
Log changes to password policy done by the OSCAP addon
and also log content of the password policy list.
Related: rhbz#1365032
=> Log password policy changes

org_fedora_oscap/gui/spokes/oscap.py, oscap-anaconda-addon.spec
Using the wait_all() function provided by the Anaconda thread manager
singleton can result in unexpected behavior, as there migh still be
threads unrelated to spoke initialization still running when the
function is called. This might result in unnecessary delay before the
OSCAP addon spoke becomes ready and installation can continue.
So use the init_done signal, which is the proper way to wait for
Anaconda spokes to finish initialization.
Also bump the Anaconda version to one that provides the init_done
signal.
Resolves: rhbz#1380224
=> Use the init_done signal instead of wait_all() (#1380224)

org_fedora_oscap/gui/spokes/oscap.glade
The warning "Overriding tab label for notebook" was caused by an empty page in the notebook. The page was removed.
The app_paintable property suppressed drawing of the upper bar's background. The property was removed.
Resolves: rhbz#1437106
=> Gtk: Fix gtk warning (#1437106)

README, docs/manual/developer_guide.adoc
This adds the beginnings of a hopefully-to-be-expanded Developer Guide. This moves the wiki page into the repo as most people don't check the wiki pages by default.
=> Add Developer Guide

tests/common_test.py, tests/ks_oscap_test.py, tests/rule_handling_test.py
- Add '--reports' to expected args in tests
- Strip whitespace in str_test
- Fix various pep8 complaints
=> Fix some failing tests and pep8 complaints

org_fedora_oscap/common.py
- pyanaconda constants module gets the product shortname whereas the product module
uses the full product name
- Fixes #38
=> Use pyanaconda constants module instead of product module

Makefile
- Makefile checks if OS is Red Hat Enterprise Linux 7 for python2 tests. If not, uses python3 tests
=> Update Makefile to handle python2 and python3 tests

org_fedora_oscap/ks/oscap.py
Fixes #36.
We copy the XCCDF, but tailoring is needed as well.
=> Don't forget to copy tailoring to new path

org_fedora_oscap/common.py, org_fedora_oscap/gui/spokes/oscap.py, org_fedora_oscap/ks/oscap.py, tests/ks_oscap_test.py
When loading content from SCAP Security Guide, we should use content from the DataStream, not from XCCDF file.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1465402
Also fixes #41
=> When using content from SSG, use the DataStream by default

org_fedora_oscap/rule_handling.py
During manual installation when profile affecting password was selected,
selection of another profile did not clear the password requirements.
The method revert_changes didn't work because the saved old password
length was overwritten each time when eval_rules was invoked.
Saved old password length should be overwritten only if the eval_rules
method is called with report_only set to False.
Fixes rhbz #1374181 and issue #52.
=> Fix password rules cleaning

org_fedora_oscap/ks/oscap.py
Fixes rhbz #1520276. Addressing:
```
Traceback (most recent call first):
File "/usr/lib64/python2.7/genericpath.py", line 18, in exists
os.stat(path)
File "/usr/share/anaconda/addons/org_fedora_oscap/ks/oscap.py", line 546, in execute
if os.path.exists(self.preinst_tailoring_path):
File "/usr/lib64/python2.7/site-packages/pyanaconda/addons.py", line 88, in execute
v.execute(storage, ksdata, instClass, users, payload)
File "/usr/lib64/python2.7/site-packages/pyanaconda/install.py", line 109, in doConfiguration
ksdata.addons.execute(storage, ksdata, instClass, u, payload)
File "/usr/lib64/python2.7/threading.py", line 765, in run
self.__target(*self.__args, **self.__kwargs)
File "/usr/lib64/python2.7/site-packages/pyanaconda/threads.py", line 227, in run
threading.Thread.run(self, *args, …
```
=> Fix a traceback in os.path.exists

Makefile, org_fedora_oscap/content_handling.py, tests/content_handling_test.py
Add tests for class DataStreamHandler
- tests for invalid path and content on object creation
- test for fetching datastream ids
- test for fetching checklist ids
- test for fetching profile ids
Also fixed `Exception AttributeError: "'DataStreamHandler' object has no attribute '_session'" in <bound method DataStreamHandler.__del__` when `dsc_file_path` points to non-existing file.
=> Add tests datastream handler

org_fedora_oscap/gui/spokes/oscap.glade, org_fedora_oscap/gui/spokes/oscap.py
UI doesn't show translations if translation domain is not defined.
Below is screenshot of UI with translations.
=> Define translation domain in OSCAPSpoke

org_fedora_oscap/rule_handling.py
Message was a source of confusion for some users attempting to create a profile. They thought it was an error and didn't realize that a missing mount point had to be created in the installation.
=> Clarify that missing partitions need to be created before selecting profile

org_fedora_oscap/rule_handling.py
- Adds new `kdump --disable` handling that can be added to anaconda scripts
to be able to disable kdump from OSCAP content
=> Add new kdump --disable rule handling

tests/test_content_handling.py
This PR adds a converted tests that were left out from #72.
The original file: https://github.com/OpenSCAP/oscap-anaconda-addon/blob/00726c1b18270c1c2da6b05f12101b2a7be7e0a8/tests/content_handling_test.py
For reference: [On pytest and exceptions](https://docs.pytest.org/en/latest/assert.html#assertions-about-expected-exceptions)
=> Added pytest conversion of the content handling test.

oscap-anaconda-addon.spec
There feeling in our team is that it is beneficial to have the upstream `.spec` files more similar to what we actually use downstream.
@redhatrises AFAIK, you were the person behind having `.spec` files to take part in PR gating, do you still like that idea? The .spec file in master and rhel7 are going to diverge.
=> Replaced the spec file with spec file closer to the RHEL7 spec.

org_fedora_oscap/rule_handling.py, tests/test_ks_oscap.py, tests/test_rule_handling.py
The Anaconda API between the `F28` and current `master` branch differs, so the OAA code also needs to be updated.
What has been done:
* The `ksdata.firewall` interface has been updated to use the `firewall_proxy` interface. There is a slight nuisance here that the proxy interface supports get/set methods, but not set operations s.a. add, difference, etc., so the code doesn't do a 100% right thing. I have decided to leave it like it is for the time being, as we are under time pressure, and the firewall settings are not used in our security content.
* The `ksdata.rootpw` has been replaced by `users_proxy` interface.
* The `storage.bootloader` has been replaced by the `bootloader_proxy` interface. Note: The interface seems to have expanded, so we can aim to set the bootloader password in the …
=> Updated the code to work with current devel Anaconda.

org_fedora_oscap/gui/spokes/oscap.py
The new Anaconda help system now operates on help ids instead of pointing to
individual files.
So drop the old property and replace it with a proper help_id.
Resolves: rhbz#1638068
=> Set help id for the OSCAP addon provided spoke (#1638068)

org_fedora_oscap/gui/spokes/oscap.py, org_fedora_oscap/ks/oscap.py, oscap-anaconda-addon.spec
Anaconda removes the install classes from the code. They are
replaced with cofiguration files.
**Depends on:** https://github.com/rhinstaller/anaconda/pull/1716
=> Remove install classes

Makefile, docs/manual/developer_guide.adoc, po/Makefile
Update development guide with available Makefile commands.
Add a warning when intltool is not installed in the system similarly to the one for when Zanata is not installed either.
=> Remove outdated Makefile help usage and update development guide.

Makefile
Package name has changed in some newer distros and causes error when
trying to pull translations.
This was based on master's code. For some reason this modification wasn't backported to rhel7-branch.
=> Enhance zanata's dependency interoperability.

oscap-anaconda-addon.spec
Pulling from Zanata every time there is a PR update is useless waste,
so tests for the upstream CI should be modified.
The run without pulling from Zanata takes 4 seconds, with pulling from Zanata it takes ~ 2 minutes and it creates traffic.
The rpmbuild is a part of CI, therefore we need to modify the spec file that is used.
=> Remove translations from upstream CI 

tests/test_rule_handling.py
In some of the `rule_handling` methods that handle kickstart rules we recently started to use new Anaconda API that uses DBUS proxy. See https://github.com/OpenSCAP/oscap-anaconda-addon/pull/81
However, after this change our upstream tests started to fail.  The problem with
upstream tests was that they don't replace the DBus proxy by a mock object and also that they mocked the old classes that aren't used in the SUT.
This PR updates our unit test by mocking the DBus proxy. We keep the mock object that is returned by `DBus.get_proxy`, modify its values and then run the code that uses these values. The test update is inspired by:
https://github.com/rhinstaller/anaconda/blob/master/tests/nosetests/pyanaconda_tests/partitioning_test.py#L48
=> Update unit tests after upgrading code to latest Anaconda code

org_fedora_oscap/gui/spokes/oscap.py
This is workaround for https://bugzilla.redhat.com/show_bug.cgi?id=1673071
Currently, Anaconda tries to translate the plugin title, but being in different translation domain prevents it to succeed. This way, we provide already translated string.
Thanks @poncovka!
=> Hack hub title to show translated.

README.md, org_fedora_oscap/common.py
This change tries to maintain compatibility with the bleeding-edge Anaconda.
=> Updated Anaconda no use network proxy instead of deprecated functionality

org_fedora_oscap/gui/spokes/oscap.glade
- Set minimal height to profile view and to the changes view.
- ~Abbreviate profile descriptions to 4-9 lines based on total profile count.~ - see #113 
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1781790
Remarks: This PR can't be tested on Fedora, as liboscap depends on gconf2 that is not part of the installed system. Putting gconf2 into the Fedora update image breaks the system completely, likely because it needs post-install scriplets to perform important tasks. The only way to test is to use a RHEL8 installation s.a. `boot.img` in a subdirectory of http://10.43.136.2/trees/rhel-8-scratch-temp/
You may not be able to get content to the addon if #111 is not merged - content is not part of that boot image, and the installer update image of 19MB seems to be too big to get …
=> Improve the OAA UX.

org_fedora_oscap/rule_handling.py, po/oscap-anaconda-addon.pot
This change introduces a mechanism that allows to vet packages marked for removal.
Such package can now have a record in the `ESSENTIAL_PACKAGES` dict (yuck, but it works), that define whether the package is essential => can't be removed based on the environment and groups selected in the Software Selection Anaconda spoke.
In RHEL8, one can't just remove e.g. xorg-common, as the system will even refuse to install.
In case when one first selects the profile and then changes the Software Selection to an incompatible setting, the Selection spoke will raise an error, as it already tries to apply the blacklist with its environment/groups.
How have I tested this change:
1. Select e.g. the RHEL8 CIS profile with e.g. minimal install. The Security Policy spoke should inform user in an ordinary …
=> Address incompatible profiles and software selections.

tests/test_rule_handling.py
The function should be able to accept other arguments.
=> Fix the mock function for DBus.get_proxy

org_fedora_oscap/gui/spokes/oscap.glade, org_fedora_oscap/gui/spokes/oscap.py
The spoke title which is defined in the Python code and visible in the hub should have capitalization that respects the local language convention.
However, the much less visible spoke label that is defined in the glade file should be uppercase, and so should be translations.
I have added a comment to the Python file, as the Glade file is machine-readable, and comments will be dropped if someone re-saves it.
See also: https://bugzilla.redhat.com/show_bug.cgi?id=1855041
=> Changed the spoke label back to uppercase.

org_fedora_oscap/common.py
=> avoiding UnicodeDecodeError in decode(), and output more errors

Makefile
Code is heavily based on contents of
https://github.com/rhinstaller/anaconda/blob/master/Makefile.am
Changes:
- Weblate is Github-based, so git and file operations are used instead of a CLI client.
- There is no push-pot, but update-pot, which leaves the latest step (git push) up to you.
Analogous PRs will have to be ported to other branches.
=> Update the language tooling from Zanata to Weblate for RHEL8

Makefile, testing_files/testing_ds.xml
Code is heavily based on contents of https://github.com/rhinstaller/anaconda/blob/master/Makefile.am
Changes:
- Weblate is Github-based, so git and file operations are used instead of a CLI client.
- There is no push-pot, but update-pot, which leaves the latest step (git push) up to you.
=> Update the language tooling from Zanata to Weblate for the RHEL7 OAA

org_fedora_oscap/gui/spokes/oscap.glade, org_fedora_oscap/gui/spokes/oscap.py, po/oscap-anaconda-addon.pot
- OAA applies security profiles and not security policy. This fixes that misnomer.
=> Replace "policy" with "profile"

org_fedora_oscap/rule_handling.py
One can get list of groups using `dnf group list --hidden`, and then get contents of a group using `dnf group info <group name or ID>`.
This should cover RHEL8 OSPP and CIS profiles.
I can't understand how the `package_iprutils_removed` fits to the mix - `iprutils` are a mandatory part of the Core group (along e.g. Bash), so I would expect this rule to break every OSPP installation.
=> Expanded group data to detect more package collisions.

org_fedora_oscap/gui/spokes/oscap.py, oscap-anaconda-addon.spec
Call `hubQ.send_ready` without the `justUpdate` argument.
The support for this argument was removed.
**Depends on:** https://github.com/rhinstaller/anaconda/pull/3028
=> Remove the justUpdate argument

Makefile, docs/manual/developer_guide.adoc, org_fedora_oscap/ks/oscap.py, tests/Dockerfile, tests/test_ks_oscap.py
Use `make container-test` to run pylint checks and unit tests in a container.
=> Allow to run tests in a container

org_fedora_oscap/common.py, org_fedora_oscap/rule_handling.py, tests/test_rule_handling.py
Don't use kickstart data to work with the Kdump add-on. The data are not
available, because the add-on has been migrated on DBus. Use the DBus API
instead.
**Related to:** https://github.com/daveyoung/kdump-anaconda-addon/pull/29
=> Use the DBus API of the Kdump add-on

org_fedora_oscap/rule_handling.py, tests/test_rule_handling.py
Don't use the `%anaconda` section of the kickstart data. Use the DBus API instead.
**Depends on:** https://github.com/rhinstaller/anaconda/pull/3099
=> Use the password policies from DBus

Makefile, org_fedora_oscap/common.py
The "fedora-latest" Anaconda diverged from the "rhel-latest", so the master branch got a bump in the major version number, and the first difference between this and the previous major versions has landed.
=> Fix the rawhide package handling

create_update_image.sh
Starting from OpenSCAP 1.3.5, OpenSCAP depends on xmlsec1 library.
Therefore, OAA needs to have these packages present in the update
img.
.#
=> Add packages

org_fedora_oscap/common.py, org_fedora_oscap/data_fetch.py, org_fedora_oscap/gui/spokes/oscap.py, tests/test_data_fetch.py
Previously, the error would be raised when the other code would try to work with the retrieved file that in fact doesn't exist. Now, the error is identified on time, and it can be communicated properly as the installation feedback.
=> Raise error when file not on the server or there is another error

tests/test_common.py, tests/test_rule_handling.py, tests/test_utils.py
The separate Python mock package has been deprecated as a result of the mock inclusion into the standard library.
=> Import mock from unittest, where it has been relocated

tests/test_data_fetch.py
The rhel8 pytest doesn't know it yet, so it shouldn't be in the RHEL8 branch.
=> Don't use the tmp_path fixture

org_fedora_oscap/common.py, org_fedora_oscap/content_discovery.py, org_fedora_oscap/content_handling.py, org_fedora_oscap/gui/spokes/oscap.py, org_fedora_oscap/rule_handling.py, org_fedora_oscap/service/installation.py, org_fedora_oscap/service/kickstart.py, org_fedora_oscap/service/oscap.py
Make all log entries identifiable easily - use the `anaconda` logger, so they are logged to the Anaconda log, and they can be grepped.
Then, fix handling of the local content when its usage is triggered by the button on the content fetch page.
Finally, remove the multiprocessing pool when evaluating files - it causes https://bugzilla.redhat.com/show_bug.cgi?id=1989434
=> Various RHEL9 improvements

org_fedora_oscap/content_discovery.py, org_fedora_oscap/ks/oscap.py
GUI downloads an archive, so the ensuing installation doesn't have to.
However, the installation has to be able to discover files recovered from the archive.
The fix makes sure that files are discovered also in subdirectories.
=> Fix archive handling in GUI installs

org_fedora_oscap/gui/spokes/oscap.py
`None` can't be passed via the DBUS interface.
There are no other obvious leftover `None`s in the GUI code - the data sent over DBUS is defined in the `apply` method of the GUI spoke.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2014108
=> Represent unselected profile by an empty string

org_fedora_oscap/service/kickstart.py
Using the old ways, the fingerprint was not propagated to the post-install kickstart.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1993065
=> Fix bad destination for the parsed content fingerprint

org_fedora_oscap/service/oscap.py
Fixes an error during installation caused during tailoring
Addressing:
dasbus.error.DBusError: Content evaluation and remediation with the oscap tool failed: OpenSCAP Error: Unable to open file: '/tmp/openscap_data/usr/share/xml/scap/sc_tailoring/tailoring-xccdf.xml' [/builddir/build/BUILD/openscap-1.3.5/src/source/oscap_source.c:288]
This is proabably a typo coming from 87509fb6ee22b6eeaa66ea4ae85ebf5abd353e14
which is only in rhel9-branch.
=> Fix tailoring

org_fedora_oscap/gui/spokes/oscap.py
Add-ons can be disabled in the Anaconda configuration files. Without the fix,
the OSCAP DBus module is started on demand by the OSCAP spoke even though it
shouldn't be activated. In the future, it will result in a failure of the
installer.
Related: rhbz#1994003
=> Don't show the OSCAP spoke if the OSCAP DBus module is disabled

tests/Dockerfile, tests/test_installation.py, tests/test_kickstart.py
* Install new dependencies in the testing container.
* Don't skip the `test_scap_security_guide` test.
* Don't skip the `test_evaluate_rules_task` test.
=> Fix and enable tests for the upstream container

org_fedora_oscap/gui/spokes/oscap.py
Anaconda is going to use a screen id to find the related help content.
**Related:** https://github.com/rhinstaller/anaconda/pull/3575
=> Use the unified help support

Makefile, create_update_image.sh, docs/manual/developer_guide.adoc, tests/Dockerfile
Run `make container-update-image` to create an update image of the OSCAP
addon and its main dependencies in a container.
Download and install the `xmlsec1-openssl` dependency for the upstream testing.
=> Allow to create an update image in a container

org_fedora_oscap/common.py, org_fedora_oscap/ks/oscap.py, tests/test_common.py
This PR fixes these related issues:
- Obvious scanner errors are communicated clearly before any serious work involving the scanner is performed.
- Errors result in installer questions rather than in tracebacks.
- The installer feedback has been adjusted to fit the installation mode, so it doesn't ask questions that can't be answered.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2007981
=> Improve UX when there are weird errors when attempting remediation

org_fedora_oscap/common.py, org_fedora_oscap/ks/oscap.py
=> Add support for the firstboot remediation - RHEL8

org_fedora_oscap/common.py, org_fedora_oscap/service/installation.py, org_fedora_oscap/service/kickstart.py, org_fedora_oscap/service/oscap.py, org_fedora_oscap/structures.py, tests/test_interface.py
OpenSCAP supports a new remediation type - a classical scan + remediate that is executed during the first boot.
This PR adds support for this functionality, and allows to control it via a remediate kickstart property.
=> Add support for the firstboot remediation

org_fedora_oscap/common.py, tests/test_common.py
Expand all string substitutions, and add a test that performs a basic sanity check of the generated config.
This is a follow-up for #190
=> Fix firstboot remediation setup

org_fedora_oscap/common.py, tests/test_common.py
Expand all string substitutions, and add a test that performs a basic sanity check of the generated config.
Port of #194 to RHEL9
=> Fix firstboot remediation setup on RHEL9

docs/manual/developer_guide.adoc
Using just "ks" is deprecated.
=> Use inst.ks in the virt-install command

org_fedora_oscap/rule_handling.py
The input of the _() function has to be a static string, and it was in those cases a formatted one, which didn't match the translation data.
How to test: Check translations of altered strings - package installed / excluded are part of even basic profiles.
=> Fix strings for translations

org_fedora_oscap/service/installation.py
oscap-utils package is not related to the firstboot remediation,
everything will continue to work even without it being an installation requirement
=> Remove the oscap-utils dependency

org_fedora_oscap/service/installation.py
oscap-utils package is not related to the firstboot remediation,
everything will continue to work even without it being an installation requirement
=> Remove oscap-utils dependency

org_fedora_oscap/common.py, org_fedora_oscap/rule_handling.py, tests/test_rule_handling.py
Anaconda is replacing `Set.*` methods with read-write properties to clean up
the DBus API and simplify unit testing with mocked DBus objects. This support
was introduced in `anaconda-37.8-1`.
=> Use Anaconda DBus read-write properties
