OpenSCAP/oscap-anaconda-addon

org_fedora_oscap/data_fetch.py
This allows for a bit more flexible resource locations and the ability to put alternate guides on the media.
=> Allow using a file:// url for any SCAP guides pushed on the media

org_fedora_oscap/common.py
See https://github.com/OpenSCAP/oscap-anaconda-addon/issues/1
How branching work in this repo? This PR could be to master, but I am not able to test it in master branch.
=> Log OpenSCAP errors

org_fedora_oscap/content_handling.py
https://bugzilla.redhat.com/show_bug.cgi?id=1256879
=> Hide "Default" profile if contains no selected rules

org_fedora_oscap/content_handling.py
Some Profile descriptions contains HTML tags to structure and format the
content and oscap-anaconda-addon has problems interpreting them.
This patch removes all HTML tags, while also trying to maintain
readability of content.
=> Parse HTML tags from SCAP content

org_fedora_oscap/common.py
=> Add HTML reports

create_update_image.sh
This is a copy paste from the wiki.
https://github.com/OpenSCAP/oscap-anaconda-addon/wiki/How-to-test-oscap-anaconda-addon
You won't need to copy paste the code from wiki anymore
if we have this code in the repository.
=> Add a script to build an update image

org_fedora_oscap/common.py
This combines the rhel7-branch and master branch way of dynamically handling product and product version in anaconda. The goal with this PR is to no longer have separate code for fedora and rhel products.
=> Dynamically handle product and product version for both RHEL and Fedora systems

docs/manual/developer_guide.adoc
The code here was moved to an executable script
create_update_image.sh in pull request #30.
=> Mention create_update_image.sh in Developer Guide

Makefile, oscap-anaconda-addon.spec
- Update .spec file to handle both python2 and python3 for RHEL and Fedora
=> Update .spec file

org_fedora_oscap/content_handling.py, org_fedora_oscap/data_fetch.py, org_fedora_oscap/gui/spokes/oscap.py, org_fedora_oscap/ks/oscap.py, org_fedora_oscap/rule_handling.py, org_fedora_oscap/utils.py, tests/data_fetch_test.py, tests/ks_oscap_test.py, tests/rule_handling_test.py, tests/utils_test.py
- Fixes a lot of pep8 complaints in code and tests.
=> More PEP8 fixes

org_fedora_oscap/content_handling.py, org_fedora_oscap/gui/spokes/oscap.py, org_fedora_oscap/rule_handling.py, tests/common_test.py, tests/ks_oscap_test.py, tests/utils_test.py
- Update code and tests to support python3
=> [master] Update to python3

docs/manual/developer_guide.adoc
The organization of the document was confused
=> Improve developer guide formating

org_fedora_oscap/rule_handling.py
The parser won't exit if it encounters something unexpected
in Ananconda remediations. Instead it will report a warning to log.
=> RHBZ#1452667: Catch Anaconda Remediations parsing errors

org_fedora_oscap/rule_handling.py
Make sure it checks for empty actions dictionary.
=> Catch KeyError

docs/manual/developer_guide.adoc
I had a problem with dependencies of unit tests. Documentation
of unit tests was missing.
=> Describe unit tests in Developer Guide

tests/rule_handling_test.py
This test should be part of PR #53, but that was already merged.
=> Add unittest for report_only parameter

tests/rule_handling_test.py
- Added asserts for other relevant values which should not be changed when report
only is True.
- Check there is no warnings in `mesages` returned by `eval_rules`.
- It seemed strange to set `self.rule_data._passwd_rules._orig_minlen` and assert it right after. So I added mock for `ksdata.anaconda.pwpolicy.get_policy()`.
=> Improve test for password rule when report only is True

org_fedora_oscap/rule_handling.py
=> Add firewall rules

Makefile, oscap-anaconda-addon.spec, po/oscap-anaconda-addon.pot
- Bump version in makefile and specfile
- Update potfile
=> Update version and translation files for release

org_fedora_oscap/common.py
=> Zipfile handling fix backport

create_update_image.sh
The script aborts the image creation procedure and prints a meaningful message whenever a step fails.
=> Improved UX of the create image script.

docs/manual/developer_guide.adoc
Added mention of `lsinitrd` and `pycurl` dependency.
=> Update of documentation.

README.md
Add Anaconda version to which this add-on is compatible.
=> Add compatible version of anaconda to rhel7 README

README.md
Add Anaconda version to which this add-on is compatible.
=> Add compatible version of anaconda to master README

org_fedora_oscap/rule_handling.py, tests/test_rule_handling.py
@jkonecny12 Could you please check this out?
=> Updated code to comply to the Bootloader proxy API.

org_fedora_oscap/gui/spokes/oscap.py
=> Updated the code to use the up-to-date Anaconda API.

org_fedora_oscap/gui/spokes/oscap.py
Resolves: rhbz#1744185
To be consistent with other spokes.
=> Do not use capitals for spoke title.

org_fedora_oscap/data_fetch.py, org_fedora_oscap/ks/oscap.py, org_fedora_oscap/rule_handling.py, oscap-anaconda-addon.spec, testing_files/testing_ds.xml, tests/test_rule_handling.py
The local storage object is no longer available. Use the DBus module instead.
**Depends on:** https://github.com/rhinstaller/anaconda/pull/2331
=> Use the DBus Storage module

org_fedora_oscap/common.py
Fix outstanding issues with changes of the underlying Anaconda API.
=> Fix compatibility with Anaconda 32.

README.md, org_fedora_oscap/gui/spokes/oscap.py, po/oscap-anaconda-addon.pot
- Merge fixes from the rhel8-branch.
- Update the potfile.
- Fix a README with current Anaconda version.
=> Prepare for the release

README.md, org_fedora_oscap/common.py, org_fedora_oscap/data_fetch.py, org_fedora_oscap/gui/spokes/oscap.glade, org_fedora_oscap/gui/spokes/oscap.py, org_fedora_oscap/ks/oscap.py, org_fedora_oscap/rule_handling.py, oscap-anaconda-addon.spec, po/oscap-anaconda-addon.pot, testing_files/testing_ds.xml, tests/test_rule_handling.py
The goal is to have RHEL8 and master branches exactly the same, as they target the same version of Anaconda.
=> Update the rhel8-branch with master commits

Makefile, po/oscap-anaconda-addon.pot
- Update the .pot file properly - the pot in 1.1 is incorrect
- Put the right version number in the `Makefile`.
=> Introduce the 1.1.1 release.

org_fedora_oscap/rule_handling.py
Removal of nfs-utils also blocks the GUI installation, see also https://bugzilla.redhat.com/show_bug.cgi?id=1787156
=> Added nfs-utils as an essential package for GUI envs.

po/oscap-anaconda-addon.pot
to reflect changes in the spoke window title done in #122
=> Updated the .pot file

Makefile
Merge only after #117 is merged.
=> Bump version after release.

org_fedora_oscap/common.py, org_fedora_oscap/rule_handling.py, org_fedora_oscap/service/installation.py, oscap-anaconda-addon.spec, tests/test_rule_handling.py
Don't use the `%packages` section of the kickstart data. Use the DBus API instead.
**Depends on:** https://github.com/rhinstaller/anaconda/pull/3029
=> Use the packages configuration data from DBus

docs/manual/developer_guide.adoc
It's an easier way of running a test VM for development and testing of OSCAP Anaconda Addon.
=> Document reanaconda

org_fedora_oscap/common.py, org_fedora_oscap/content_handling.py, org_fedora_oscap/data_fetch.py
Recommended review workflow is to go by commits - each of them addresses a specific improvements, but it would be too small for a standalone PR.
=> Introduce various small fixes and refactoring

tests/test_rule_handling.py
There are some tests that use a mock of the local storage object, but this
object is no longer available and it is always None. Test a mock a DBus
proxy instead.
=> Fix some of the storage-related tests

AUTHORS, org_fedora_oscap/common.py, org_fedora_oscap/cpioarchive.py
The Python cpio module was not properly maintained upstream.
The LGPL license allows to relicence the derivative work under GPL - see LGPL section 3 or http://www.gnu.org/licenses/gpl-faq.html#AllCompatibility
=> Merge the cpio module into the addon

Makefile, org_fedora_oscap/common.py, org_fedora_oscap/content_discovery.py, org_fedora_oscap/cpioarchive.py, org_fedora_oscap/gui/spokes/oscap.py, org_fedora_oscap/service/installation.py, org_fedora_oscap/service/kickstart.py, org_fedora_oscap/service/oscap.py, tests/test_installation.py, tests/test_interface.py, tests/test_kickstart.py
- Try to make it not only a "fedora" addon, but also a proper "rhel" addon.
- Take away the fingerprint verification task - that one is inseparable from the content fetch.
- Reuse the `PolicyData` structure in the kickstart.
- Change the question in case something goes wrong during the installation.
- Properly convert messages to strings when printing them.
- Handle the case when the content has been already fetched during the first phase - in that case, just be sure to come up with an error if the content is defective.
=> Polish some aspects of the addon

org_fedora_oscap/content_discovery.py, org_fedora_oscap/ks/oscap.py
This is a sister PR of #159 that fixes fatal omissions not discovered during testing so far.
=> Fix multiple small RHEL8 issues

org_fedora_oscap/content_handling.py
Don't use the multiprocessing pool - it sometimes creates probems during its initialization: https://bugzilla.redhat.com/show_bug.cgi?id=1989441
=> Refactor content identification

org_fedora_oscap/content_discovery.py, po/oscap-anaconda-addon.pot
The only useful thing was #168.
The `pot` file update is based on a manual regeneration based on the actual source.
=> Merge rhel8-branch into rhel9-branch

org_fedora_oscap/gui/spokes/oscap.py
Port #169 to the RHEL9 branch
Related: rhbz#1994003
=> Don't show the OSCAP spoke if the OSCAP DBus module is disabled

Makefile, create_update_image.sh, docs/manual/developer_guide.adoc, tests/Dockerfile
=> Rhel9 - create update image in a container

org_fedora_oscap/common.py, org_fedora_oscap/service/installation.py, tests/test_common.py, tests/test_installation.py
=> Check oscap sanity rhel9

org_fedora_oscap/gui/spokes/oscap.py
Port of #175 to RHEL9 that should fix https://bugzilla.redhat.com/show_bug.cgi?id=2043512
The help feature itself depends on https://bugzilla.redhat.com/show_bug.cgi?id=1995945 that is not even ON_QA yet, so the only way how to review the BZ for the time being is sanity-only check, i.e. it probably doesn't break anything, while it could, in theory, fix the issue.
=> Unified help rhel9

org_fedora_oscap/common.py, org_fedora_oscap/service/installation.py, tests/test_common.py, tests/test_installation.py
=> Check oscap sanity rawhide

org_fedora_oscap/service/oscap.py
Port of #180 into the rawhide branch
=> Fix tailoring

tests/Dockerfile, tests/test_installation.py, tests/test_kickstart.py
=> Rhel9 update container tests

docs/manual/developer_guide.adoc, testing_files/basic_rhel8_kickstart.cfg
- describes method using virt-install
- adds an example kickstart
=> Document testing of OAA with KS

org_fedora_oscap/common.py, org_fedora_oscap/service/installation.py, org_fedora_oscap/service/kickstart.py, org_fedora_oscap/service/oscap.py, org_fedora_oscap/structures.py, tests/test_common.py, tests/test_interface.py
Basically port #189 and #194 to Fedora.
=> Introduce firstboot remediation to Fedora

org_fedora_oscap/common.py, org_fedora_oscap/service/kickstart.py, tests/test_kickstart.py, tests/test_service_kickstart.py
=> Tests cleanup

.github/workflows/build.yaml, .packit.yaml, Makefile, oscap-anaconda-addon.spec
Build RPM on all supported Fedora versions using Packit service.
=> Add Packit configuration

.github/workflows/build.yaml, .packit.yaml, oscap-anaconda-addon.spec
Build RPM on CentOS Stream 9 using Packit service.
=> Add Packit configuration (RHEL9 branch)

org_fedora_oscap/common.py, org_fedora_oscap/ks/oscap.py, tests/test_common.py
It is not possible to iron out all UX issues that introduction of such feature introduces.
=> Revert the firstboot remediation - RHEL8

org_fedora_oscap/service/oscap.py, tests/test_interface.py
The firstboot remediation is very disruptive
=> Dont remediate using firstboot by default
